language: python

sudo: false

branches:
    only:
        - master

env:
    global:
        - secure: "gcgOvzJsHQEB+6rQlKNDAgprS2vHlqDftywEHRTLVmmTOAPfcJr0ffamtnotEmGJZ1ivc5xsRqel18U9eXxqstYTFxKC2EVb1SfO0W3cQ8NDd6WI5fj1QASdvqixUHiENh3TbwLZ9XWIp2hDXdxs9NNT4/K623CabQgi8cSXCNw2gIeb+3ed4hy/0mDTNt+qt6A7cAXMDZ3PwXWZ00r1anC7lbWqPAEd7/stmVe7UKmwbP4h+utCCZg8zHvtJzqqU9n8CHveMWFsUdOd+1xcYAEYxVy7rBYdSgeu+/hrKOT0B2ArS6mesLLqk2KSe4UO1Aoh7KvyxxkNsxeWW0gx4Zig6DS/EYnk7OLEelwx5+A9QF36cfyRSNNquETkHUOSBE87LiEAuBpRFJSdL7WwmHyA8zziK3QK5VXdrmIeOyWM0AipJHeP6nkzoKC4r2JnW3jcmzYRtqV+MWewNZ/wUnZQl0mfyg9KG2hHjH+u0+oFUeQUHehJC6HTmdlSQKRntooyeTBdp6NigQxERJKZHcQ73Kwl3JXObmwAzZpHZnRCOoWcIZczgNdLaaHgCD3Nsm1nhJZClBHFtCvHQUhihtahxC0BGY/+vEdviuL1MsbnF5sZvmCjnZ6fUqKrVG0mptdluu6mKirQrEgbtSTH3uCfe2579N5neE/QJ/KWn34="

    matrix:
        - CONDA_PY=27  FEATURE_OLDGLIBC=0
        - CONDA_PY=36  FEATURE_OLDGLIBC=0
        - CONDA_PY=35  FEATURE_OLDGLIBC=1

install:
    - |
      if [ ! -f ${HOME}/miniconda3/bin/conda ] ; then
          echo "Fresh miniconda install..."
          MINICONDA_URL="https://repo.continuum.io/miniconda"
          if [ `uname` == "Darwin" ]; then
              MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
          else
              MINICONDA_FILE="Miniconda3-latest-Linux-x86_64.sh"
          fi
          wget ${MINICONDA_URL}/${MINICONDA_FILE}
          rm -rf ${HOME}/miniconda3
          bash ${MINICONDA_FILE} -b -p ${HOME}/miniconda3
      fi
      export PATH=${HOME}/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      
      conda update --yes conda
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-build anaconda-client

script:
    - |
      set -e
      
      # build
      conda build ./recipe
      
      # upload
      anaconda -t ${CONDA_UPLOAD_TOKEN} upload -u pywr ${HOME}/miniconda3/conda-bld/linux-64/*.tar.bz2 --force
