environment:
    CONDA_UPLOAD_TOKEN:
        secure: qgP92GRS8WQsvxiUGJ6eoNcqY7Qu6nP9SkQi5yM+aPI2CbCv2y13kAIl+6sE3HqD
    
    matrix:
        - TARGET_ARCH: x64
          CONDA_PY: 34
          CONDA_NPY: 110
          CONDA_INSTALL_LOCN: C:\\Miniconda35-x64
        
        - TARGET_ARCH: x64
          CONDA_PY: 36
          CONDA_NPY: 112
          CONDA_INSTALL_LOCN: C:\\Miniconda35-x64

platform:
    - x64

install:
    # cygwin breaks conda-build
    - cmd: rmdir C:\cygwin /s /q
    
    # activate conda
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
    - cmd: set PYTHONUNBUFFERED=1

    # add our channels
    - cmd: conda config --set show_channel_urls true
    - cmd: conda config --add channels conda-forge
    - cmd: conda config --add channels snorfalorpagus

    # install build tools
    - cmd: conda install -n root --quiet --yes conda-build anaconda-client

# Skip .NET project specific build phase.
build: off

test_script:
    - cmd: conda build recipe --quiet
    - cmd: anaconda -t %CONDA_UPLOAD_TOKEN% upload -u pywr %CONDA_INSTALL_LOCN%\conda-bld\win-64\*.tar.bz2 --force
