{% set name = "pywr" %}
{% set version = "0.2" %}
{% set build_number = "0" %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    path: pywr/

build:
    number: {{ build_number }}

requirements:
    build:
        - python
        - setuptools
        - numpy x.x
        - cython
        - glpk
        - lpsolve
        - future
        - packaging
    
    run:
        - python
        - numpy x.x
        - pandas
        - networkx
        - glpk
        - lpsolve
        - pytables
        - xlrd
        - scipy
        - future
        - packaging

test:
    requires:
        - pytest
    source_files:
        - tests/*

about:
    home: https://github.com/pywr/pywr
    license: GPL
    license_file: LICENSE.txt
    summary:  Pywr is a generalised network resource allocation model written in Python.
